---
name: version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to cut

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        id: import_gpg
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name: ${{ secrets.GIT_USER_NAME }}
          git_committer_email: ${{ secrets.GIT_USER_EMAIL }}
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.5
      - name: Setup Poetry
        uses: gr1n/setup-poetry@v2
      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-
      - name: Set config
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git remote set-url --push origin "https://${GH_USER}:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
      - name: Install dependencies
        run: poetry install
      - name: Cut version
        run: |
          poetry run bump2version --sign-tags ${{ github.event.inputs.version }}
          git push && git push --tags
